export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT';
export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const CHANGE_EMPLOYEES_COUNT = 'CHANGE_EMPLOYEES_COUNT';
export const SET_USER = 'SET_USER';
