export const REPORT_DIALOG_CHANGE_DEPARTMENT = 'REPORT_DIALOG_CHANGE_DEPARTMENT';
export const REPORT_DIALOG_CHANGE_MEASURE = 'REPORT_DIALOG_CHANGE_MEASURE';
export const REPORT_DIALOG_CHANGE_CHART = 'REPORT_DIALOG_CHANGE_CHART';
export const REPORT_DIALOG_CHANGE_TIMEFRAME = 'REPORT_DIALOG_CHANGE_TIMEFRAME';
