export const REPORT_DIALOG_OPEN = 'REPORT_DIALOG_OPEN';
export const REPORT_DIALOG_CLOSE = 'REPORT_DIALOG_CLOSE';
export const REPORT_DIALOG_CHANGE_DEPARTMENT = 'REPORT_DIALOG_CHANGE_DEPARTMENT';
export const REPORT_DIALOG_CHANGE_MEASURE = 'REPORT_DIALOG_CHANGE_MEASURE';
export const REPORT_DIALOG_CHANGE_CHART = 'REPORT_DIALOG_CHANGE_CHART';
export const REPORT_DIALOG_CHANGE_TIMEFRAME = 'REPORT_DIALOG_CHANGE_TIMEFRAME';
export const REPORT_DIALOG_ADD_TO_REPORT = 'REPORT_DIALOG_ADD_TO_REPORT';
export const REPORT_PAGE_DATA_FETCHED = 'REPORT_PAGE_DATA_FETCHED';
